package com.company.speedment.test.f1app.db0.f1app.pitstops;

import com.speedment.Entity;
import com.speedment.field.ComparableField;
import com.speedment.field.StringField;
import com.speedment.internal.core.field.ComparableFieldImpl;
import com.speedment.internal.core.field.StringFieldImpl;
import java.sql.Time;
import java.util.Optional;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the
 * com.speedment.internal.ui.config.TableProperty@56bc73.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public interface PitStops extends Entity<PitStops> {
    
    /**
     * This Field corresponds to the {@link PitStops} field that can be obtained
     * using the {@link PitStops#getRaceId()} method.
     */
    public final static ComparableField<PitStops, Integer> RACEID = new ComparableFieldImpl<>("raceId", PitStops::getRaceId, PitStops::setRaceId);
    /**
     * This Field corresponds to the {@link PitStops} field that can be obtained
     * using the {@link PitStops#getDriverId()} method.
     */
    public final static ComparableField<PitStops, Integer> DRIVERID = new ComparableFieldImpl<>("driverId", PitStops::getDriverId, PitStops::setDriverId);
    /**
     * This Field corresponds to the {@link PitStops} field that can be obtained
     * using the {@link PitStops#getStop()} method.
     */
    public final static ComparableField<PitStops, Integer> STOP = new ComparableFieldImpl<>("stop", PitStops::getStop, PitStops::setStop);
    /**
     * This Field corresponds to the {@link PitStops} field that can be obtained
     * using the {@link PitStops#getLap()} method.
     */
    public final static ComparableField<PitStops, Integer> LAP = new ComparableFieldImpl<>("lap", PitStops::getLap, PitStops::setLap);
    /**
     * This Field corresponds to the {@link PitStops} field that can be obtained
     * using the {@link PitStops#getTime()} method.
     */
    public final static ComparableField<PitStops, Time> TIME = new ComparableFieldImpl<>("time", PitStops::getTime, PitStops::setTime);
    /**
     * This Field corresponds to the {@link PitStops} field that can be obtained
     * using the {@link PitStops#getDuration()} method.
     */
    public final static StringField<PitStops> DURATION = new StringFieldImpl<>("duration", o -> o.getDuration().orElse(null), PitStops::setDuration);
    /**
     * This Field corresponds to the {@link PitStops} field that can be obtained
     * using the {@link PitStops#getMilliseconds()} method.
     */
    public final static ComparableField<PitStops, Integer> MILLISECONDS = new ComparableFieldImpl<>("milliseconds", o -> o.getMilliseconds().orElse(null), PitStops::setMilliseconds);
    
    /**
     * Returns the raceId of this PitStops. The raceId field corresponds to the
     * database column db0.F1APP.pitStops.raceId.
     * 
     * @return the raceId of this PitStops
     */
    Integer getRaceId();
    
    /**
     * Returns the driverId of this PitStops. The driverId field corresponds to
     * the database column db0.F1APP.pitStops.driverId.
     * 
     * @return the driverId of this PitStops
     */
    Integer getDriverId();
    
    /**
     * Returns the stop of this PitStops. The stop field corresponds to the
     * database column db0.F1APP.pitStops.stop.
     * 
     * @return the stop of this PitStops
     */
    Integer getStop();
    
    /**
     * Returns the lap of this PitStops. The lap field corresponds to the
     * database column db0.F1APP.pitStops.lap.
     * 
     * @return the lap of this PitStops
     */
    Integer getLap();
    
    /**
     * Returns the time of this PitStops. The time field corresponds to the
     * database column db0.F1APP.pitStops.time.
     * 
     * @return the time of this PitStops
     */
    Time getTime();
    
    /**
     * Returns the duration of this PitStops. The duration field corresponds to
     * the database column db0.F1APP.pitStops.duration.
     * 
     * @return the duration of this PitStops
     */
    Optional<String> getDuration();
    
    /**
     * Returns the milliseconds of this PitStops. The milliseconds field
     * corresponds to the database column db0.F1APP.pitStops.milliseconds.
     * 
     * @return the milliseconds of this PitStops
     */
    Optional<Integer> getMilliseconds();
    
    /**
     * Sets the raceId of this PitStops. The raceId field corresponds to the
     * database column db0.F1APP.pitStops.raceId.
     * 
     * @param raceId to set of this PitStops
     * @return this PitStops instance
     */
    PitStops setRaceId(Integer raceId);
    
    /**
     * Sets the driverId of this PitStops. The driverId field corresponds to the
     * database column db0.F1APP.pitStops.driverId.
     * 
     * @param driverId to set of this PitStops
     * @return this PitStops instance
     */
    PitStops setDriverId(Integer driverId);
    
    /**
     * Sets the stop of this PitStops. The stop field corresponds to the database
     * column db0.F1APP.pitStops.stop.
     * 
     * @param stop to set of this PitStops
     * @return this PitStops instance
     */
    PitStops setStop(Integer stop);
    
    /**
     * Sets the lap of this PitStops. The lap field corresponds to the database
     * column db0.F1APP.pitStops.lap.
     * 
     * @param lap to set of this PitStops
     * @return this PitStops instance
     */
    PitStops setLap(Integer lap);
    
    /**
     * Sets the time of this PitStops. The time field corresponds to the database
     * column db0.F1APP.pitStops.time.
     * 
     * @param time to set of this PitStops
     * @return this PitStops instance
     */
    PitStops setTime(Time time);
    
    /**
     * Sets the duration of this PitStops. The duration field corresponds to the
     * database column db0.F1APP.pitStops.duration.
     * 
     * @param duration to set of this PitStops
     * @return this PitStops instance
     */
    PitStops setDuration(String duration);
    
    /**
     * Sets the milliseconds of this PitStops. The milliseconds field corresponds
     * to the database column db0.F1APP.pitStops.milliseconds.
     * 
     * @param milliseconds to set of this PitStops
     * @return this PitStops instance
     */
    PitStops setMilliseconds(Integer milliseconds);
}