package com.company.speedment.test.f1app.db0.f1app.seasons;

import com.speedment.Entity;
import com.speedment.field.ComparableField;
import com.speedment.field.StringField;
import com.speedment.internal.core.field.ComparableFieldImpl;
import com.speedment.internal.core.field.StringFieldImpl;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the
 * com.speedment.internal.ui.config.TableProperty@bd1d217.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public interface Seasons extends Entity<Seasons> {
    
    /**
     * This Field corresponds to the {@link Seasons} field that can be obtained
     * using the {@link Seasons#getYear()} method.
     */
    public final static ComparableField<Seasons, Integer> YEAR = new ComparableFieldImpl<>("year", Seasons::getYear, Seasons::setYear);
    /**
     * This Field corresponds to the {@link Seasons} field that can be obtained
     * using the {@link Seasons#getUrl()} method.
     */
    public final static StringField<Seasons> URL = new StringFieldImpl<>("url", Seasons::getUrl, Seasons::setUrl);
    
    /**
     * Returns the year of this Seasons. The year field corresponds to the
     * database column db0.F1APP.seasons.year.
     * 
     * @return the year of this Seasons
     */
    Integer getYear();
    
    /**
     * Returns the url of this Seasons. The url field corresponds to the database
     * column db0.F1APP.seasons.url.
     * 
     * @return the url of this Seasons
     */
    String getUrl();
    
    /**
     * Sets the year of this Seasons. The year field corresponds to the database
     * column db0.F1APP.seasons.year.
     * 
     * @param year to set of this Seasons
     * @return this Seasons instance
     */
    Seasons setYear(Integer year);
    
    /**
     * Sets the url of this Seasons. The url field corresponds to the database
     * column db0.F1APP.seasons.url.
     * 
     * @param url to set of this Seasons
     * @return this Seasons instance
     */
    Seasons setUrl(String url);
}