package com.company.speedment.test.f1app.db0.f1app.constructors.impl;

import com.company.speedment.test.f1app.db0.f1app.constructors.Constructors;
import com.speedment.Speedment;
import com.speedment.config.Column;
import com.speedment.config.Table;
import com.speedment.config.mapper.TypeMapper;
import com.speedment.exception.SpeedmentException;
import com.speedment.internal.core.config.mapper.identity.IntegerIdentityMapper;
import com.speedment.internal.core.config.mapper.identity.StringIdentityMapper;
import com.speedment.internal.core.manager.sql.AbstractSqlManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.annotation.Generated;

/**
 * A manager implementation representing an entity (for example, a row) in
 * the com.speedment.internal.ui.config.TableProperty@286108bf.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class ConstructorsManagerImpl extends AbstractSqlManager<Constructors> {
    
    private final TypeMapper<Integer, Integer> constructorIdTypeMapper = new IntegerIdentityMapper();
    private final TypeMapper<String, String> constructorRefTypeMapper = new StringIdentityMapper();
    private final TypeMapper<String, String> nameTypeMapper = new StringIdentityMapper();
    private final TypeMapper<String, String> nationalityTypeMapper = new StringIdentityMapper();
    private final TypeMapper<String, String> urlTypeMapper = new StringIdentityMapper();
    
    public ConstructorsManagerImpl(Speedment speedment) {
        super(speedment);
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public Class<Constructors> getEntityClass() {
        return Constructors.class;
    }
    
    @Override
    public Object get(Constructors entity, Column column) {
        switch (column.getName()) {
            case "constructorId" : return entity.getConstructorId();
            case "constructorRef" : return entity.getConstructorRef();
            case "name" : return entity.getName();
            case "nationality" : return entity.getNationality();
            case "url" : return entity.getUrl();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    public void set(Constructors entity, Column column, Object value) {
        switch (column.getName()) {
            case "constructorId" : entity.setConstructorId((Integer) value); break;
            case "constructorRef" : entity.setConstructorRef((String) value); break;
            case "name" : entity.setName((String) value); break;
            case "nationality" : entity.setNationality((String) value); break;
            case "url" : entity.setUrl((String) value); break;
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    public Table getTable() {
        return speedment.getProjectComponent().getProject().findTableByName("db0.F1APP.constructors");
    }
    
    protected Constructors defaultReadEntity(ResultSet resultSet) {
        final Constructors entity = newInstance();
        try {
            entity.setConstructorId(constructorIdTypeMapper.toJavaType(resultSet.getInt(1)));
            entity.setConstructorRef(constructorRefTypeMapper.toJavaType(resultSet.getString(2)));
            entity.setName(nameTypeMapper.toJavaType(resultSet.getString(3)));
            entity.setNationality(nationalityTypeMapper.toJavaType(resultSet.getString(4)));
            entity.setUrl(urlTypeMapper.toJavaType(resultSet.getString(5)));
        }
        catch (SQLException sqle) {
            throw new SpeedmentException(sqle);
        }
        return entity;
    }
    
    @Override
    public Constructors newInstance() {
        return new ConstructorsImpl(speedment);
    }
    
    @Override
    public Integer primaryKeyFor(Constructors entity) {
        return entity.getConstructorId();
    }
}