package com.company.speedment.test.f1app;

import com.company.speedment.test.f1app.db0.f1app.circuits.impl.CircuitsManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.constructorresults.impl.ConstructorResultsManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.constructors.impl.ConstructorsManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.constructorstandings.impl.ConstructorStandingsManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.drivers.impl.DriversManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.driverstandings.impl.DriverStandingsManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.imagesdrivers.impl.ImagesDriversManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.laptimes.impl.LapTimesManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.pitstops.impl.PitStopsManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.qualifying.impl.QualifyingManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.races.impl.RacesManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.results.impl.ResultsManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.seasons.impl.SeasonsManagerImpl;
import com.company.speedment.test.f1app.db0.f1app.status.impl.StatusManagerImpl;
import com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle;
import javax.annotation.Generated;

/**
 * A {@link
 * com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle} class
 * for the {@link com.speedment.config.Project} named f1app.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class F1appApplication extends SpeedmentApplicationLifecycle<F1appApplication> {
    
    public F1appApplication() {
        setSpeedmentApplicationMetadata(new F1appApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        super.onInit();
        loadAndSetProject();
        put(new ImagesDriversManagerImpl(speedment));
        put(new CircuitsManagerImpl(speedment));
        put(new ConstructorResultsManagerImpl(speedment));
        put(new ConstructorStandingsManagerImpl(speedment));
        put(new ConstructorsManagerImpl(speedment));
        put(new DriverStandingsManagerImpl(speedment));
        put(new DriversManagerImpl(speedment));
        put(new LapTimesManagerImpl(speedment));
        put(new PitStopsManagerImpl(speedment));
        put(new QualifyingManagerImpl(speedment));
        put(new RacesManagerImpl(speedment));
        put(new ResultsManagerImpl(speedment));
        put(new SeasonsManagerImpl(speedment));
        put(new StatusManagerImpl(speedment));
    }
}