package com.company.speedment.test.f1app.db0.f1app.imagesdrivers;

import com.speedment.Entity;
import com.speedment.field.ComparableField;
import com.speedment.field.StringField;
import com.speedment.internal.core.field.ComparableFieldImpl;
import com.speedment.internal.core.field.StringFieldImpl;
import java.util.Optional;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table
 * 'f1app.db0.F1APP.ImagesDrivers'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public interface ImagesDrivers extends Entity<ImagesDrivers> {
    
    /**
     * This Field corresponds to the {@link ImagesDrivers} field that can be
     * obtained using the {@link ImagesDrivers#getDriverImageId()} method.
     */
    public final static ComparableField<ImagesDrivers, Integer> DRIVERIMAGEID = new ComparableFieldImpl<>("driverImageId", ImagesDrivers::getDriverImageId, ImagesDrivers::setDriverImageId);
    /**
     * This Field corresponds to the {@link ImagesDrivers} field that can be
     * obtained using the {@link ImagesDrivers#getDriverDisplayImage()} method.
     */
    public final static StringField<ImagesDrivers> DRIVERDISPLAYIMAGE = new StringFieldImpl<>("driverDisplayImage", o -> o.getDriverDisplayImage().orElse(null), ImagesDrivers::setDriverDisplayImage);
    /**
     * This Field corresponds to the {@link ImagesDrivers} field that can be
     * obtained using the {@link ImagesDrivers#getDriverHelmet()} method.
     */
    public final static StringField<ImagesDrivers> DRIVERHELMET = new StringFieldImpl<>("driverHelmet", o -> o.getDriverHelmet().orElse(null), ImagesDrivers::setDriverHelmet);
    
    /**
     * Returns the driverImageId of this ImagesDrivers. The driverImageId field
     * corresponds to the database column db0.F1APP.ImagesDrivers.driverImageId.
     * 
     * @return the driverImageId of this ImagesDrivers
     */
    Integer getDriverImageId();
    
    /**
     * Returns the driverDisplayImage of this ImagesDrivers. The
     * driverDisplayImage field corresponds to the database column
     * db0.F1APP.ImagesDrivers.driverDisplayImage.
     * 
     * @return the driverDisplayImage of this ImagesDrivers
     */
    Optional<String> getDriverDisplayImage();
    
    /**
     * Returns the driverHelmet of this ImagesDrivers. The driverHelmet field
     * corresponds to the database column db0.F1APP.ImagesDrivers.driverHelmet.
     * 
     * @return the driverHelmet of this ImagesDrivers
     */
    Optional<String> getDriverHelmet();
    
    /**
     * Sets the driverImageId of this ImagesDrivers. The driverImageId field
     * corresponds to the database column db0.F1APP.ImagesDrivers.driverImageId.
     * 
     * @param driverImageId to set of this ImagesDrivers
     * @return this ImagesDrivers instance
     */
    ImagesDrivers setDriverImageId(Integer driverImageId);
    
    /**
     * Sets the driverDisplayImage of this ImagesDrivers. The driverDisplayImage
     * field corresponds to the database column
     * db0.F1APP.ImagesDrivers.driverDisplayImage.
     * 
     * @param driverDisplayImage to set of this ImagesDrivers
     * @return this ImagesDrivers instance
     */
    ImagesDrivers setDriverDisplayImage(String driverDisplayImage);
    
    /**
     * Sets the driverHelmet of this ImagesDrivers. The driverHelmet field
     * corresponds to the database column db0.F1APP.ImagesDrivers.driverHelmet.
     * 
     * @param driverHelmet to set of this ImagesDrivers
     * @return this ImagesDrivers instance
     */
    ImagesDrivers setDriverHelmet(String driverHelmet);
}